In [1]:
import pandas as pd

# Cargar el archivo CSV
df = pd.read_csv('../1.2 csvs_raw/cities_stations_20240625_223537.csv')

In [2]:
df

,names,comunity,scores,dates,co,humidity,no2,o3,p,pm10,pm25,so2,temp,wind
0,Madrid,Madrid,70,2024-06-26T05:09:47+09:00,0.1,60.0,11.5,48.4,1009.9,42.0,70.0,1.6,28.8,1.0
1,"Cuatro Caminos, Madrid, Spain",Madrid,119,2024-06-26T05:05:48+09:00,NaN,60.0,25.6,NaN,1009.9,51.0,119.0,NaN,26.6,1.0
2,"Sanchinarro, Madrid, Spain",Madrid,91,2024-06-26T05:05:53+09:00,NaN,62.0,12.4,NaN,1007.6,41.0,91.0,NaN,26.1,3.2
3,"Plaza De Castilla, Madrid, Spain",Madrid,89,2024-06-26T05:05:49+09:00,NaN,60.0,16.5,NaN,1009.9,43.0,89.0,NaN,26.6,1.0
4,"Castellana, Madrid, Spain",Madrid,70,2024-06-26T05:05:53+09:00,NaN,60.0,11.5,NaN,1009.9,42.0,70.0,NaN,26.6,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
169,"Tlalnepantla, México, Mexico",NaN,70,2023-09-10T05:40:18+09:00,4.5,28.0,9.3,49.6,1026.5,40.0,70.0,2.9,24.0,1.5
170,"Tlaneplantla, México, Mexico",NaN,-,2021-12-18T06:32:04+09:00,NaN,54.0,NaN,NaN,1007.0,NaN,NaN,NaN,20.0,11.0
171,"Tultitlan, México, Mexico",NaN,-,2023-06-30T23:43:12+09:00,NaN,59.0,NaN,NaN,1027.7,NaN,NaN,NaN,19.0,1.5
172,"Camarones, México, Mexico",NaN,-,2023-08-30T22:44:39+09:00,NaN,62.0,NaN,NaN,1027.4,NaN,NaN,NaN,12.0,2.5
173,"Velódromo, Puebla, Mexico",NaN,98,2024-06-12T12:14:02+09:00,18.0,46.0,11.5,23.2,1024.0,70.0,98.0,1.3,21.0,7.2

In [3]:
df['dates'] = pd.to_datetime(df['dates'])
df['fecha_convertida'] = df['dates'] - pd.Timedelta(hours=7)

# Crear las nuevas columnas 'Dia' y 'Hora'
df['Dia'] = df['fecha_convertida'].dt.date
df['Hora'] = df['fecha_convertida'].dt.hour

print(df)

                                names comunity scores  \
0                              Madrid   Madrid     70
1       Cuatro Caminos, Madrid, Spain   Madrid    119
2          Sanchinarro, Madrid, Spain   Madrid     91
3    Plaza De Castilla, Madrid, Spain   Madrid     89
4           Castellana, Madrid, Spain   Madrid     70
..                                ...      ...    ...
169      Tlalnepantla, México, Mexico      NaN     70
170      Tlaneplantla, México, Mexico      NaN      -
171         Tultitlan, México, Mexico      NaN      -
172         Camarones, México, Mexico      NaN      -
173         Velódromo, Puebla, Mexico      NaN     98

                        dates    co  humidity   no2    o3       p  pm10  \
0   2024-06-26 05:09:47+09:00   0.1      60.0  11.5  48.4  1009.9  42.0
1   2024-06-26 05:05:48+09:00   NaN      60.0  25.6   NaN  1009.9  51.0
2   2024-06-26 05:05:53+09:00   NaN      62.0  12.4   NaN  1007.6  41.0
3   2024-06-26 05:05:49+09:00   NaN      60.0  16.5   NaN  1009.9  43.0
4   2024-06-26 05:05:53+09:00   NaN      60.0  11.5   NaN  1009.9  42.0
..                        ...   ...       ...   ...   ...     ...   ...
169 2023-09-10 05:40:18+09:00   4.5      28.0   9.3  49.6  1026.5  40.0
170 2021-12-18 06:32:04+09:00   NaN      54.0   NaN   NaN  1007.0   NaN
171 2023-06-30 23:43:12+09:00   NaN      59.0   NaN   NaN  1027.7   NaN
172 2023-08-30 22:44:39+09:00   NaN      62.0   NaN   NaN  1027.4   NaN
173 2024-06-12 12:14:02+09:00  18.0      46.0  11.5  23.2  1024.0  70.0

      pm25  so2  temp  wind          fecha_convertida         Dia  Hora
0     70.0  1.6  28.8   1.0 2024-06-25 22:09:47+09:00  2024-06-25  22.0
1    119.0  NaN  26.6   1.0 2024-06-25 22:05:48+09:00  2024-06-25  22.0
2     91.0  NaN  26.1   3.2 2024-06-25 22:05:53+09:00  2024-06-25  22.0
3     89.0  NaN  26.6   1.0 2024-06-25 22:05:49+09:00  2024-06-25  22.0
4     70.0  NaN  26.6   1.0 2024-06-25 22:05:53+09:00  2024-06-25  22.0
..     ...  ...   ...   ...                       ...         ...   ...
169   70.0  2.9  24.0   1.5 2023-09-09 22:40:18+09:00  2023-09-09  22.0
170    NaN  NaN  20.0  11.0 2021-12-17 23:32:04+09:00  2021-12-17  23.0
171    NaN  NaN  19.0   1.5 2023-06-30 16:43:12+09:00  2023-06-30  16.0
172    NaN  NaN  12.0   2.5 2023-08-30 15:44:39+09:00  2023-08-30  15.0
173   98.0  1.3  21.0   7.2 2024-06-12 05:14:02+09:00  2024-06-12   5.0

[174 rows x 17 columns]

## SEPARAR FECHA Y HORA Y CATEGORIZAR ESTA ULTIMA

In [4]:
# Función para categorizar la hora
def categorizar_hora(hora):
    if 6 <= hora < 12:
        return 'mañana'
    elif 12 <= hora < 15:
        return 'mediodia'
    elif 15 <= hora < 20:
        return 'tarde'
    elif 20 <= hora < 24:
        return 'noche'
    else:
        return 'otro'

# Aplicar la función a la columna 'hora'
df['periodo'] = df['Hora'].apply(categorizar_hora)

# Eliminar la columna 'hora' original, ya que no se necesita más
# df = df.drop(columns=['hora'])

In [5]:
df.head(30)

,names,comunity,scores,dates,co,humidity,no2,o3,p,pm10,pm25,so2,temp,wind,fecha_convertida,Dia,Hora,periodo
0,Madrid,Madrid,70,2024-06-26 05:09:47+09:00,0.1,60.0,11.5,48.4,1009.9,42.0,70.0,1.6,28.8,1.0,2024-06-25 22:09:47+09:00,2024-06-25,22.0,noche
1,"Cuatro Caminos, Madrid, Spain",Madrid,119,2024-06-26 05:05:48+09:00,NaN,60.0,25.6,NaN,1009.9,51.0,119.0,NaN,26.6,1.0,2024-06-25 22:05:48+09:00,2024-06-25,22.0,noche
2,"Sanchinarro, Madrid, Spain",Madrid,91,2024-06-26 05:05:53+09:00,NaN,62.0,12.4,NaN,1007.6,41.0,91.0,NaN,26.1,3.2,2024-06-25 22:05:53+09:00,2024-06-25,22.0,noche
3,"Plaza De Castilla, Madrid, Spain",Madrid,89,2024-06-26 05:05:49+09:00,NaN,60.0,16.5,NaN,1009.9,43.0,89.0,NaN,26.6,1.0,2024-06-25 22:05:49+09:00,2024-06-25,22.0,noche
4,"Castellana, Madrid, Spain",Madrid,70,2024-06-26 05:05:53+09:00,NaN,60.0,11.5,NaN,1009.9,42.0,70.0,NaN,26.6,1.0,2024-06-25 22:05:53+09:00,2024-06-25,22.0,noche
5,"Fernandez Ladreda, Madrid, Spain",Madrid,50,2024-06-26 04:51:01+09:00,NaN,34.0,17.9,NaN,1009.0,19.0,50.0,NaN,30.5,0.5,2024-06-25 21:51:01+09:00,2024-06-25,21.0,noche
6,"Casa De Campo, Madrid, Spain",Madrid,44,2024-06-26 05:05:48+09:00,NaN,60.0,3.7,43.5,1009.9,6.0,5.0,NaN,26.6,1.0,2024-06-25 22:05:48+09:00,2024-06-25,22.0,noche
7,"Escuelas Aguirre, Madrid, Spain",Madrid,40,2024-06-26 05:05:48+09:00,0.1,60.0,12.8,40.3,1009.9,30.0,50.0,1.6,26.6,1.0,2024-06-25 22:05:48+09:00,2024-06-25,22.0,noche
8,"Plaza Elíptica, Madrid, Spain",Madrid,30,2024-06-26 05:05:49+09:00,0.1,34.0,18.8,NaN,1009.0,15.0,30.0,NaN,30.5,0.5,2024-06-25 22:05:49+09:00,2024-06-25,22.0,noche
9,"Mendez Alvaro, Madrid, Spain",Madrid,25,2024-06-26 05:05:52+09:00,NaN,40.0,8.3,NaN,1008.6,7.0,25.0,NaN,28.8,1.0,2024-06-25 22:05:52+09:00,2024-06-25,22.0,noche
10,"Media Red, Madrid, Spain",Madrid,-,2021-12-18 06:32:00+09:00,NaN,88.0,NaN,NaN,1025.9,NaN,NaN,NaN,7.7,1.7,2021-12-17 23:32:00+09:00,2021-12-17,23.0,noche
11,"el atazar, Madrid, Spain",Madrid,42,2024-06-26 04:56:57+09:00,NaN,57.8,1.4,41.5,1011.8,12.0,42.0,1.1,25.2,0.3,2024-06-25 21:56:57+09:00,2024-06-25,21.0,noche
12,"algete, Madrid, Spain",Madrid,64,2024-06-26 04:56:49+09:00,NaN,51.0,3.7,63.6,1006.1,NaN,53.0,NaN,26.0,3.4,2024-06-25 21:56:49+09:00,2024-06-25,21.0,noche
13,"alcorcón, Madrid, Spain",Madrid,46,2024-06-26 04:56:52+09:00,NaN,34.0,4.6,42.3,1009.0,NaN,46.0,NaN,30.5,0.5,2024-06-25 21:56:52+09:00,2024-06-25,21.0,noche
14,"valdemoro, Madrid, Spain",Madrid,42,2024-06-26 04:56:57+09:00,NaN,40.0,6.0,41.9,1008.0,NaN,42.0,NaN,30.5,1.0,2024-06-25 21:56:57+09:00,2024-06-25,21.0,noche
15,"torrejon de ardoz, Madrid, Spain",Madrid,57,2024-06-26 04:56:55+09:00,NaN,44.5,7.8,45.5,1008.0,22.0,57.0,NaN,26.5,4.8,2024-06-25 21:56:55+09:00,2024-06-25,21.0,noche
16,"villa del prado, Madrid, Spain",Madrid,59,2024-06-26 04:56:48+09:00,NaN,55.0,1.4,46.3,1003.0,19.0,59.0,1.1,26.1,1.0,2024-06-25 21:56:48+09:00,2024-06-25,21.0,noche
17,"collado villalba, Madrid, Spain",Madrid,42,2024-06-26 04:56:50+09:00,NaN,43.7,6.9,38.2,1006.6,NaN,42.0,0.6,27.5,0.5,2024-06-25 21:56:50+09:00,2024-06-25,21.0,noche
18,"villarejo de salvanes, Madrid, Spain",Madrid,44,2024-06-26 04:56:50+09:00,NaN,39.3,2.8,44.3,1011.9,NaN,34.0,NaN,29.8,2.3,2024-06-25 21:56:50+09:00,2024-06-25,21.0,noche
19,"San Nicolas, Canarias, Spain",Canarias,25,2024-06-26 05:20:50+09:00,0.1,63.3,1.0,20.4,1009.8,12.0,25.0,0.6,22.1,12.3,2024-06-25 22:20:50+09:00,2024-06-25,22.0,noche
20,"Mercado Central, Canarias, Spain",Canarias,25,2024-06-26 05:20:50+09:00,0.1,63.3,2.3,15.1,1009.8,13.0,25.0,0.6,22.1,12.3,2024-06-25 22:20:50+09:00,2024-06-25,22.0,noche
21,"Lezcano, Canarias, Spain",Canarias,25,2024-06-26 04:56:56+09:00,0.1,65.5,2.8,24.0,1009.4,16.0,25.0,2.1,22.8,10.2,2024-06-25 21:56:56+09:00,2024-06-25,21.0,noche
22,"La Loma-Telde, Canarias, Spain",Canarias,24,2024-06-26 04:56:51+09:00,0.1,65.5,2.8,23.6,1009.4,23.0,17.0,2.6,22.8,10.2,2024-06-25 21:56:51+09:00,2024-06-25,21.0,noche
23,"Jinamar fase 3, Canarias, Spain",Canarias,23,2024-06-26 04:56:49+09:00,0.1,65.5,2.8,22.8,1009.4,16.0,9.0,2.1,22.8,10.2,2024-06-25 21:56:49+09:00,2024-06-25,21.0,noche
24,"Nestor Alamo, Canarias, Spain",Canarias,21,2024-06-26 05:20:50+09:00,0.1,63.3,4.2,19.1,1009.8,14.0,21.0,0.6,22.1,12.3,2024-06-25 22:20:50+09:00,2024-06-25,22.0,noche
25,"Barcelona, Catalunya, Spain",Catalunya,35,2024-06-26 05:22:11+09:00,0.1,71.0,1.0,35.4,1013.4,14.0,30.0,0.6,21.1,1.5,2024-06-25 22:22:11+09:00,2024-06-25,22.0,noche
26,"Barcelona (Palau Reial), Catalunya, Spain",Catalunya,34,2024-06-26 05:22:10+09:00,0.1,71.0,5.5,33.8,1013.4,14.0,30.0,1.1,21.1,1.5,2024-06-25 22:22:10+09:00,2024-06-25,22.0,noche
27,"l'Hospitalet de Llobregat, Catalunya, Spain",Catalunya,34,2024-06-26 05:22:11+09:00,0.1,71.0,6.0,33.8,1013.4,21.0,30.0,1.1,21.1,1.5,2024-06-25 22:22:11+09:00,2024-06-25,22.0,noche
28,"Barcelona (Parc Vall d'Hebrón), Catalunya, Spain",Catalunya,33,2024-06-26 05:22:09+09:00,0.1,71.0,4.2,32.9,1013.4,18.0,25.0,0.6,21.1,1.5,2024-06-25 22:22:09+09:00,2024-06-25,22.0,noche
29,"Sant Adrià de Besòs, Catalunya, Spain",Catalunya,31,2024-06-26 05:22:10+09:00,NaN,74.0,6.4,30.5,1012.3,20.0,NaN,NaN,23.3,2.5,2024-06-25 22:22:10+09:00,2024-06-25,22.0,noche

## CATEGORIZAR CALIDAD DEL AIRE

In [6]:
def categorizar_calidad_aire(score):
    if score <= 50:
        return 'Buena'
    elif score <= 100:
        return 'Moderada'
    elif score <= 150:
        return 'Dañina a la Salud de los Grupos Sensitivos'
    elif score <= 200:
        return 'Dañina a la Salud'
    elif score <= 300:
        return 'Muy Dañina a la Salud'
    else:
        return 'Arriesgado'

In [7]:
# Aplicar la función a la columna 'scores'
df['calidad_aire'] = df['scores'].apply(lambda x: categorizar_calidad_aire(float(x)) if x != '-' else '-')

In [8]:
# Reordenar las columnas para que 'fecha' y 'periodo' estén juntas
df = df[['names', 'comunity', 'scores','calidad_aire', 'fecha_convertida', 'periodo', 'co', 'humidity', 'no2', 'o3', 'p', 'pm10', 'pm25', 'so2', 'temp', 'wind']]

In [9]:
df.head()

,names,comunity,scores,calidad_aire,fecha_convertida,periodo,co,humidity,no2,o3,p,pm10,pm25,so2,temp,wind
0,Madrid,Madrid,70,Moderada,2024-06-25 22:09:47+09:00,noche,0.1,60.0,11.5,48.4,1009.9,42.0,70.0,1.6,28.8,1.0
1,"Cuatro Caminos, Madrid, Spain",Madrid,119,Dañina a la Salud de los Grupos Sensitivos,2024-06-25 22:05:48+09:00,noche,NaN,60.0,25.6,NaN,1009.9,51.0,119.0,NaN,26.6,1.0
2,"Sanchinarro, Madrid, Spain",Madrid,91,Moderada,2024-06-25 22:05:53+09:00,noche,NaN,62.0,12.4,NaN,1007.6,41.0,91.0,NaN,26.1,3.2
3,"Plaza De Castilla, Madrid, Spain",Madrid,89,Moderada,2024-06-25 22:05:49+09:00,noche,NaN,60.0,16.5,NaN,1009.9,43.0,89.0,NaN,26.6,1.0
4,"Castellana, Madrid, Spain",Madrid,70,Moderada,2024-06-25 22:05:53+09:00,noche,NaN,60.0,11.5,NaN,1009.9,42.0,70.0,NaN,26.6,1.0